<?php
/**
 * Conferenceplus
 *
 * @package    Conferenceplus
 * @author     Robert Deutz <rdeutz@googlemail.com>
 *
 * @copyright  2014 JandBeyond
 * @license    GNU General Public License version 2 or later
 **/


namespace Conferenceplus\Country;

class Helper
{
    protected $data = array(
        4 => array('name' => 'Afghanistan','numeric-codes' => 4,'alpha-2-codes' => 'AF','alpha-3-codes' => 'AFG'),
        248 => array('name' => 'Åland Islands','numeric-codes' => 248,'alpha-2-codes' => 'AX','alpha-3-codes' => 'ALA'),
        8 => array('name' => 'Albania','numeric-codes' => 8,'alpha-2-codes' => 'AL','alpha-3-codes' => 'ALB'),
        12 => array('name' => 'Algeria','numeric-codes' => 12,'alpha-2-codes' => 'DZ','alpha-3-codes' => 'DZA'),
        16 => array('name' => 'American Samoa','numeric-codes' => 16,'alpha-2-codes' => 'AS','alpha-3-codes' => 'ASM'),
        20 => array('name' => 'Andorra','numeric-codes' => 20,'alpha-2-codes' => 'AD','alpha-3-codes' => 'AND'),
        24 => array('name' => 'Angola','numeric-codes' => 24,'alpha-2-codes' => 'AO','alpha-3-codes' => 'AGO'),
        660 => array('name' => 'Anguilla','numeric-codes' => 660,'alpha-2-codes' => 'AI','alpha-3-codes' => 'AIA'),
        10 => array('name' => 'Antarctica','numeric-codes' => 10,'alpha-2-codes' => 'AQ','alpha-3-codes' => 'ATA'),
        28 => array('name' => 'Antigua and Barbuda','numeric-codes' => 28,'alpha-2-codes' => 'AG','alpha-3-codes' => 'ATG'),
        32 => array('name' => 'Argentina','numeric-codes' => 32,'alpha-2-codes' => 'AR','alpha-3-codes' => 'ARG'),
        51 => array('name' => 'Armenia','numeric-codes' => 51,'alpha-2-codes' => 'AM','alpha-3-codes' => 'ARM'),
        533 => array('name' => 'Aruba','numeric-codes' => 533,'alpha-2-codes' => 'AW','alpha-3-codes' => 'ABW'),
        36 => array('name' => 'Australia','numeric-codes' => 36,'alpha-2-codes' => 'AU','alpha-3-codes' => 'AUS'),
        40 => array('name' => 'Austria','numeric-codes' => 40,'alpha-2-codes' => 'AT','alpha-3-codes' => 'AUT'),
        31 => array('name' => 'Azerbaijan','numeric-codes' => 31,'alpha-2-codes' => 'AZ','alpha-3-codes' => 'AZE'),
        44 => array('name' => 'Bahamas','numeric-codes' => 44,'alpha-2-codes' => 'BS','alpha-3-codes' => 'BHS'),
        48 => array('name' => 'Bahrain','numeric-codes' => 48,'alpha-2-codes' => 'BH','alpha-3-codes' => 'BHR'),
        50 => array('name' => 'Bangladesh','numeric-codes' => 50,'alpha-2-codes' => 'BD','alpha-3-codes' => 'BGD'),
        52 => array('name' => 'Barbados','numeric-codes' => 52,'alpha-2-codes' => 'BB','alpha-3-codes' => 'BRB'),
        112 => array('name' => 'Belarus','numeric-codes' => 112,'alpha-2-codes' => 'BY','alpha-3-codes' => 'BLR'),
        56 => array('name' => 'Belgium','numeric-codes' => 56,'alpha-2-codes' => 'BE','alpha-3-codes' => 'BEL'),
        84 => array('name' => 'Belize','numeric-codes' => 84,'alpha-2-codes' => 'BZ','alpha-3-codes' => 'BLZ'),
        204 => array('name' => 'Benin','numeric-codes' => 204,'alpha-2-codes' => 'BJ','alpha-3-codes' => 'BEN'),
        60 => array('name' => 'Bermuda','numeric-codes' => 60,'alpha-2-codes' => 'BM','alpha-3-codes' => 'BMU'),
        64 => array('name' => 'Bhutan','numeric-codes' => 64,'alpha-2-codes' => 'BT','alpha-3-codes' => 'BTN'),
        68 => array('name' => 'Bolivia, Plurinational State of','numeric-codes' => 68,'alpha-2-codes' => 'BO','alpha-3-codes' => 'BOL'),
        535 => array('name' => 'Bonaire, Sint Eustatius and Saba','numeric-codes' => 535,'alpha-2-codes' => 'BQ','alpha-3-codes' => 'BES'),
        70 => array('name' => 'Bosnia and Herzegovina','numeric-codes' => 70,'alpha-2-codes' => 'BA','alpha-3-codes' => 'BIH'),
        72 => array('name' => 'Botswana','numeric-codes' => 72,'alpha-2-codes' => 'BW','alpha-3-codes' => 'BWA'),
        74 => array('name' => 'Bouvet Island','numeric-codes' => 74,'alpha-2-codes' => 'BV','alpha-3-codes' => 'BVT'),
        76 => array('name' => 'Brazil','numeric-codes' => 76,'alpha-2-codes' => 'BR','alpha-3-codes' => 'BRA'),
        86 => array('name' => 'British Indian Ocean Territory','numeric-codes' => 86,'alpha-2-codes' => 'IO','alpha-3-codes' => 'IOT'),
        96 => array('name' => 'Brunei Darussalam','numeric-codes' => 96,'alpha-2-codes' => 'BN','alpha-3-codes' => 'BRN'),
        100 => array('name' => 'Bulgaria','numeric-codes' => 100,'alpha-2-codes' => 'BG','alpha-3-codes' => 'BGR'),
        854 => array('name' => 'Burkina Faso','numeric-codes' => 854,'alpha-2-codes' => 'BF','alpha-3-codes' => 'BFA'),
        108 => array('name' => 'Burundi','numeric-codes' => 108,'alpha-2-codes' => 'BI','alpha-3-codes' => 'BDI'),
        116 => array('name' => 'Cambodia','numeric-codes' => 116,'alpha-2-codes' => 'KH','alpha-3-codes' => 'KHM'),
        120 => array('name' => 'Cameroon','numeric-codes' => 120,'alpha-2-codes' => 'CM','alpha-3-codes' => 'CMR'),
        124 => array('name' => 'Canada','numeric-codes' => 124,'alpha-2-codes' => 'CA','alpha-3-codes' => 'CAN'),
        132 => array('name' => 'Cape Verde','numeric-codes' => 132,'alpha-2-codes' => 'CV','alpha-3-codes' => 'CPV'),
        136 => array('name' => 'Cayman Islands','numeric-codes' => 136,'alpha-2-codes' => 'KY','alpha-3-codes' => 'CYM'),
        140 => array('name' => 'Central African Republic','numeric-codes' => 140,'alpha-2-codes' => 'CF','alpha-3-codes' => 'CAF'),
        148 => array('name' => 'Chad','numeric-codes' => 148,'alpha-2-codes' => 'TD','alpha-3-codes' => 'TCD'),
        152 => array('name' => 'Chile','numeric-codes' => 152,'alpha-2-codes' => 'CL','alpha-3-codes' => 'CHL'),
        156 => array('name' => 'China','numeric-codes' => 156,'alpha-2-codes' => 'CN','alpha-3-codes' => 'CHN'),
        162 => array('name' => 'Christmas Island','numeric-codes' => 162,'alpha-2-codes' => 'CX','alpha-3-codes' => 'CXR'),
        166 => array('name' => 'Cocos (Keeling) Islands','numeric-codes' => 166,'alpha-2-codes' => 'CC','alpha-3-codes' => 'CCK'),
        170 => array('name' => 'Colombia','numeric-codes' => 170,'alpha-2-codes' => 'CO','alpha-3-codes' => 'COL'),
        174 => array('name' => 'Comoros','numeric-codes' => 174,'alpha-2-codes' => 'KM','alpha-3-codes' => 'COM'),
        178 => array('name' => 'Congo','numeric-codes' => 178,'alpha-2-codes' => 'CG','alpha-3-codes' => 'COG'),
        180 => array('name' => 'Congo, the Democratic Republic of the','numeric-codes' => 180,'alpha-2-codes' => 'CD','alpha-3-codes' => 'COD'),
        184 => array('name' => 'Cook Islands','numeric-codes' => 184,'alpha-2-codes' => 'CK','alpha-3-codes' => 'COK'),
        188 => array('name' => 'Costa Rica','numeric-codes' => 188,'alpha-2-codes' => 'CR','alpha-3-codes' => 'CRI'),
        384 => array('name' => 'Côte d\'Ivoire','numeric-codes' => 384,'alpha-2-codes' => 'CI','alpha-3-codes' => 'CIV'),
        191 => array('name' => 'Croatia','numeric-codes' => 191,'alpha-2-codes' => 'HR','alpha-3-codes' => 'HRV'),
        192 => array('name' => 'Cuba','numeric-codes' => 192,'alpha-2-codes' => 'CU','alpha-3-codes' => 'CUB'),
        531 => array('name' => 'Curaçao','numeric-codes' => 531,'alpha-2-codes' => 'CW','alpha-3-codes' => 'CUW'),
        196 => array('name' => 'Cyprus','numeric-codes' => 196,'alpha-2-codes' => 'CY','alpha-3-codes' => 'CYP'),
        203 => array('name' => 'Czech Republic','numeric-codes' => 203,'alpha-2-codes' => 'CZ','alpha-3-codes' => 'CZE'),
        208 => array('name' => 'Denmark','numeric-codes' => 208,'alpha-2-codes' => 'DK','alpha-3-codes' => 'DNK'),
        262 => array('name' => 'Djibouti','numeric-codes' => 262,'alpha-2-codes' => 'DJ','alpha-3-codes' => 'DJI'),
        212 => array('name' => 'Dominica','numeric-codes' => 212,'alpha-2-codes' => 'DM','alpha-3-codes' => 'DMA'),
        214 => array('name' => 'Dominican Republic','numeric-codes' => 214,'alpha-2-codes' => 'DO','alpha-3-codes' => 'DOM'),
        218 => array('name' => 'Ecuador','numeric-codes' => 218,'alpha-2-codes' => 'EC','alpha-3-codes' => 'ECU'),
        818 => array('name' => 'Egypt','numeric-codes' => 818,'alpha-2-codes' => 'EG','alpha-3-codes' => 'EGY'),
        222 => array('name' => 'El Salvador','numeric-codes' => 222,'alpha-2-codes' => 'SV','alpha-3-codes' => 'SLV'),
        226 => array('name' => 'Equatorial Guinea','numeric-codes' => 226,'alpha-2-codes' => 'GQ','alpha-3-codes' => 'GNQ'),
        232 => array('name' => 'Eritrea','numeric-codes' => 232,'alpha-2-codes' => 'ER','alpha-3-codes' => 'ERI'),
        233 => array('name' => 'Estonia','numeric-codes' => 233,'alpha-2-codes' => 'EE','alpha-3-codes' => 'EST'),
        231 => array('name' => 'Ethiopia','numeric-codes' => 231,'alpha-2-codes' => 'ET','alpha-3-codes' => 'ETH'),
        238 => array('name' => 'Falkland Islands (Malvinas)','numeric-codes' => 238,'alpha-2-codes' => 'FK','alpha-3-codes' => 'FLK'),
        234 => array('name' => 'Faroe Islands','numeric-codes' => 234,'alpha-2-codes' => 'FO','alpha-3-codes' => 'FRO'),
        242 => array('name' => 'Fiji','numeric-codes' => 242,'alpha-2-codes' => 'FJ','alpha-3-codes' => 'FJI'),
        246 => array('name' => 'Finland','numeric-codes' => 246,'alpha-2-codes' => 'FI','alpha-3-codes' => 'FIN'),
        250 => array('name' => 'France','numeric-codes' => 250,'alpha-2-codes' => 'FR','alpha-3-codes' => 'FRA'),
        254 => array('name' => 'French Guiana','numeric-codes' => 254,'alpha-2-codes' => 'GF','alpha-3-codes' => 'GUF'),
        258 => array('name' => 'French Polynesia','numeric-codes' => 258,'alpha-2-codes' => 'PF','alpha-3-codes' => 'PYF'),
        260 => array('name' => 'French Southern Territories','numeric-codes' => 260,'alpha-2-codes' => 'TF','alpha-3-codes' => 'ATF'),
        266 => array('name' => 'Gabon','numeric-codes' => 266,'alpha-2-codes' => 'GA','alpha-3-codes' => 'GAB'),
        270 => array('name' => 'Gambia','numeric-codes' => 270,'alpha-2-codes' => 'GM','alpha-3-codes' => 'GMB'),
        268 => array('name' => 'Georgia','numeric-codes' => 268,'alpha-2-codes' => 'GE','alpha-3-codes' => 'GEO'),
        276 => array('name' => 'Germany','numeric-codes' => 276,'alpha-2-codes' => 'DE','alpha-3-codes' => 'DEU'),
        288 => array('name' => 'Ghana','numeric-codes' => 288,'alpha-2-codes' => 'GH','alpha-3-codes' => 'GHA'),
        292 => array('name' => 'Gibraltar','numeric-codes' => 292,'alpha-2-codes' => 'GI','alpha-3-codes' => 'GIB'),
        300 => array('name' => 'Greece','numeric-codes' => 300,'alpha-2-codes' => 'GR','alpha-3-codes' => 'GRC'),
        304 => array('name' => 'Greenland','numeric-codes' => 304,'alpha-2-codes' => 'GL','alpha-3-codes' => 'GRL'),
        308 => array('name' => 'Grenada','numeric-codes' => 308,'alpha-2-codes' => 'GD','alpha-3-codes' => 'GRD'),
        312 => array('name' => 'Guadeloupe','numeric-codes' => 312,'alpha-2-codes' => 'GP','alpha-3-codes' => 'GLP'),
        316 => array('name' => 'Guam','numeric-codes' => 316,'alpha-2-codes' => 'GU','alpha-3-codes' => 'GUM'),
        320 => array('name' => 'Guatemala','numeric-codes' => 320,'alpha-2-codes' => 'GT','alpha-3-codes' => 'GTM'),
        831 => array('name' => 'Guernsey','numeric-codes' => 831,'alpha-2-codes' => 'GG','alpha-3-codes' => 'GGY'),
        324 => array('name' => 'Guinea','numeric-codes' => 324,'alpha-2-codes' => 'GN','alpha-3-codes' => 'GIN'),
        624 => array('name' => 'Guinea-Bissau','numeric-codes' => 624,'alpha-2-codes' => 'GW','alpha-3-codes' => 'GNB'),
        328 => array('name' => 'Guyana','numeric-codes' => 328,'alpha-2-codes' => 'GY','alpha-3-codes' => 'GUY'),
        332 => array('name' => 'Haiti','numeric-codes' => 332,'alpha-2-codes' => 'HT','alpha-3-codes' => 'HTI'),
        334 => array('name' => 'Heard Island and McDonald Islands','numeric-codes' => 334,'alpha-2-codes' => 'HM','alpha-3-codes' => 'HMD'),
        336 => array('name' => 'Holy See (Vatican City State)','numeric-codes' => 336,'alpha-2-codes' => 'VA','alpha-3-codes' => 'VAT'),
        340 => array('name' => 'Honduras','numeric-codes' => 340,'alpha-2-codes' => 'HN','alpha-3-codes' => 'HND'),
        344 => array('name' => 'Hong Kong','numeric-codes' => 344,'alpha-2-codes' => 'HK','alpha-3-codes' => 'HKG'),
        348 => array('name' => 'Hungary','numeric-codes' => 348,'alpha-2-codes' => 'HU','alpha-3-codes' => 'HUN'),
        352 => array('name' => 'Iceland','numeric-codes' => 352,'alpha-2-codes' => 'IS','alpha-3-codes' => 'ISL'),
        356 => array('name' => 'India','numeric-codes' => 356,'alpha-2-codes' => 'IN','alpha-3-codes' => 'IND'),
        360 => array('name' => 'Indonesia','numeric-codes' => 360,'alpha-2-codes' => 'ID','alpha-3-codes' => 'IDN'),
        364 => array('name' => 'Iran, Islamic Republic of','numeric-codes' => 364,'alpha-2-codes' => 'IR','alpha-3-codes' => 'IRN'),
        368 => array('name' => 'Iraq','numeric-codes' => 368,'alpha-2-codes' => 'IQ','alpha-3-codes' => 'IRQ'),
        372 => array('name' => 'Ireland','numeric-codes' => 372,'alpha-2-codes' => 'IE','alpha-3-codes' => 'IRL'),
        833 => array('name' => 'Isle of Man','numeric-codes' => 833,'alpha-2-codes' => 'IM','alpha-3-codes' => 'IMN'),
        376 => array('name' => 'Israel','numeric-codes' => 376,'alpha-2-codes' => 'IL','alpha-3-codes' => 'ISR'),
        380 => array('name' => 'Italy','numeric-codes' => 380,'alpha-2-codes' => 'IT','alpha-3-codes' => 'ITA'),
        388 => array('name' => 'Jamaica','numeric-codes' => 388,'alpha-2-codes' => 'JM','alpha-3-codes' => 'JAM'),
        392 => array('name' => 'Japan','numeric-codes' => 392,'alpha-2-codes' => 'JP','alpha-3-codes' => 'JPN'),
        832 => array('name' => 'Jersey','numeric-codes' => 832,'alpha-2-codes' => 'JE','alpha-3-codes' => 'JEY'),
        400 => array('name' => 'Jordan','numeric-codes' => 400,'alpha-2-codes' => 'JO','alpha-3-codes' => 'JOR'),
        398 => array('name' => 'Kazakhstan','numeric-codes' => 398,'alpha-2-codes' => 'KZ','alpha-3-codes' => 'KAZ'),
        404 => array('name' => 'Kenya','numeric-codes' => 404,'alpha-2-codes' => 'KE','alpha-3-codes' => 'KEN'),
        296 => array('name' => 'Kiribati','numeric-codes' => 296,'alpha-2-codes' => 'KI','alpha-3-codes' => 'KIR'),
        408 => array('name' => 'Korea, Democratic People\'s Republic of','numeric-codes' => 408,'alpha-2-codes' => 'KP','alpha-3-codes' => 'PRK'),
        410 => array('name' => 'Korea, Republic of','numeric-codes' => 410,'alpha-2-codes' => 'KR','alpha-3-codes' => 'KOR'),
        414 => array('name' => 'Kuwait','numeric-codes' => 414,'alpha-2-codes' => 'KW','alpha-3-codes' => 'KWT'),
        417 => array('name' => 'Kyrgyzstan','numeric-codes' => 417,'alpha-2-codes' => 'KG','alpha-3-codes' => 'KGZ'),
        418 => array('name' => 'Lao People\'s Democratic Republic','numeric-codes' => 418,'alpha-2-codes' => 'LA','alpha-3-codes' => 'LAO'),
        428 => array('name' => 'Latvia','numeric-codes' => 428,'alpha-2-codes' => 'LV','alpha-3-codes' => 'LVA'),
        422 => array('name' => 'Lebanon','numeric-codes' => 422,'alpha-2-codes' => 'LB','alpha-3-codes' => 'LBN'),
        426 => array('name' => 'Lesotho','numeric-codes' => 426,'alpha-2-codes' => 'LS','alpha-3-codes' => 'LSO'),
        430 => array('name' => 'Liberia','numeric-codes' => 430,'alpha-2-codes' => 'LR','alpha-3-codes' => 'LBR'),
        434 => array('name' => 'Libya','numeric-codes' => 434,'alpha-2-codes' => 'LY','alpha-3-codes' => 'LBY'),
        438 => array('name' => 'Liechtenstein','numeric-codes' => 438,'alpha-2-codes' => 'LI','alpha-3-codes' => 'LIE'),
        440 => array('name' => 'Lithuania','numeric-codes' => 440,'alpha-2-codes' => 'LT','alpha-3-codes' => 'LTU'),
        442 => array('name' => 'Luxembourg','numeric-codes' => 442,'alpha-2-codes' => 'LU','alpha-3-codes' => 'LUX'),
        446 => array('name' => 'Macao','numeric-codes' => 446,'alpha-2-codes' => 'MO','alpha-3-codes' => 'MAC'),
        807 => array('name' => 'Macedonia, the former Yugoslav Republic of','numeric-codes' => 807,'alpha-2-codes' => 'MK','alpha-3-codes' => 'MKD'),
        450 => array('name' => 'Madagascar','numeric-codes' => 450,'alpha-2-codes' => 'MG','alpha-3-codes' => 'MDG'),
        454 => array('name' => 'Malawi','numeric-codes' => 454,'alpha-2-codes' => 'MW','alpha-3-codes' => 'MWI'),
        458 => array('name' => 'Malaysia','numeric-codes' => 458,'alpha-2-codes' => 'MY','alpha-3-codes' => 'MYS'),
        462 => array('name' => 'Maldives','numeric-codes' => 462,'alpha-2-codes' => 'MV','alpha-3-codes' => 'MDV'),
        466 => array('name' => 'Mali','numeric-codes' => 466,'alpha-2-codes' => 'ML','alpha-3-codes' => 'MLI'),
        470 => array('name' => 'Malta','numeric-codes' => 470,'alpha-2-codes' => 'MT','alpha-3-codes' => 'MLT'),
        584 => array('name' => 'Marshall Islands','numeric-codes' => 584,'alpha-2-codes' => 'MH','alpha-3-codes' => 'MHL'),
        474 => array('name' => 'Martinique','numeric-codes' => 474,'alpha-2-codes' => 'MQ','alpha-3-codes' => 'MTQ'),
        478 => array('name' => 'Mauritania','numeric-codes' => 478,'alpha-2-codes' => 'MR','alpha-3-codes' => 'MRT'),
        480 => array('name' => 'Mauritius','numeric-codes' => 480,'alpha-2-codes' => 'MU','alpha-3-codes' => 'MUS'),
        175 => array('name' => 'Mayotte','numeric-codes' => 175,'alpha-2-codes' => 'YT','alpha-3-codes' => 'MYT'),
        484 => array('name' => 'Mexico','numeric-codes' => 484,'alpha-2-codes' => 'MX','alpha-3-codes' => 'MEX'),
        583 => array('name' => 'Micronesia, Federated States of','numeric-codes' => 583,'alpha-2-codes' => 'FM','alpha-3-codes' => 'FSM'),
        498 => array('name' => 'Moldova, Republic of','numeric-codes' => 498,'alpha-2-codes' => 'MD','alpha-3-codes' => 'MDA'),
        492 => array('name' => 'Monaco','numeric-codes' => 492,'alpha-2-codes' => 'MC','alpha-3-codes' => 'MCO'),
        496 => array('name' => 'Mongolia','numeric-codes' => 496,'alpha-2-codes' => 'MN','alpha-3-codes' => 'MNG'),
        499 => array('name' => 'Montenegro','numeric-codes' => 499,'alpha-2-codes' => 'ME','alpha-3-codes' => 'MNE'),
        500 => array('name' => 'Montserrat','numeric-codes' => 500,'alpha-2-codes' => 'MS','alpha-3-codes' => 'MSR'),
        504 => array('name' => 'Morocco','numeric-codes' => 504,'alpha-2-codes' => 'MA','alpha-3-codes' => 'MAR'),
        508 => array('name' => 'Mozambique','numeric-codes' => 508,'alpha-2-codes' => 'MZ','alpha-3-codes' => 'MOZ'),
        104 => array('name' => 'Myanmar','numeric-codes' => 104,'alpha-2-codes' => 'MM','alpha-3-codes' => 'MMR'),
        516 => array('name' => 'Namibia','numeric-codes' => 516,'alpha-2-codes' => 'NA','alpha-3-codes' => 'NAM'),
        520 => array('name' => 'Nauru','numeric-codes' => 520,'alpha-2-codes' => 'NR','alpha-3-codes' => 'NRU'),
        524 => array('name' => 'Nepal','numeric-codes' => 524,'alpha-2-codes' => 'NP','alpha-3-codes' => 'NPL'),
        528 => array('name' => 'Netherlands','numeric-codes' => 528,'alpha-2-codes' => 'NL','alpha-3-codes' => 'NLD'),
        540 => array('name' => 'New Caledonia','numeric-codes' => 540,'alpha-2-codes' => 'NC','alpha-3-codes' => 'NCL'),
        554 => array('name' => 'New Zealand','numeric-codes' => 554,'alpha-2-codes' => 'NZ','alpha-3-codes' => 'NZL'),
        558 => array('name' => 'Nicaragua','numeric-codes' => 558,'alpha-2-codes' => 'NI','alpha-3-codes' => 'NIC'),
        562 => array('name' => 'Niger','numeric-codes' => 562,'alpha-2-codes' => 'NE','alpha-3-codes' => 'NER'),
        566 => array('name' => 'Nigeria','numeric-codes' => 566,'alpha-2-codes' => 'NG','alpha-3-codes' => 'NGA'),
        570 => array('name' => 'Niue','numeric-codes' => 570,'alpha-2-codes' => 'NU','alpha-3-codes' => 'NIU'),
        574 => array('name' => 'Norfolk Island','numeric-codes' => 574,'alpha-2-codes' => 'NF','alpha-3-codes' => 'NFK'),
        580 => array('name' => 'Northern Mariana Islands','numeric-codes' => 580,'alpha-2-codes' => 'MP','alpha-3-codes' => 'MNP'),
        578 => array('name' => 'Norway','numeric-codes' => 578,'alpha-2-codes' => 'NO','alpha-3-codes' => 'NOR'),
        512 => array('name' => 'Oman','numeric-codes' => 512,'alpha-2-codes' => 'OM','alpha-3-codes' => 'OMN'),
        586 => array('name' => 'Pakistan','numeric-codes' => 586,'alpha-2-codes' => 'PK','alpha-3-codes' => 'PAK'),
        585 => array('name' => 'Palau','numeric-codes' => 585,'alpha-2-codes' => 'PW','alpha-3-codes' => 'PLW'),
        275 => array('name' => 'Palestinian Territory, Occupied','numeric-codes' => 275,'alpha-2-codes' => 'PS','alpha-3-codes' => 'PSE'),
        591 => array('name' => 'Panama','numeric-codes' => 591,'alpha-2-codes' => 'PA','alpha-3-codes' => 'PAN'),
        598 => array('name' => 'Papua New Guinea','numeric-codes' => 598,'alpha-2-codes' => 'PG','alpha-3-codes' => 'PNG'),
        600 => array('name' => 'Paraguay','numeric-codes' => 600,'alpha-2-codes' => 'PY','alpha-3-codes' => 'PRY'),
        604 => array('name' => 'Peru','numeric-codes' => 604,'alpha-2-codes' => 'PE','alpha-3-codes' => 'PER'),
        608 => array('name' => 'Philippines','numeric-codes' => 608,'alpha-2-codes' => 'PH','alpha-3-codes' => 'PHL'),
        612 => array('name' => 'Pitcairn','numeric-codes' => 612,'alpha-2-codes' => 'PN','alpha-3-codes' => 'PCN'),
        616 => array('name' => 'Poland','numeric-codes' => 616,'alpha-2-codes' => 'PL','alpha-3-codes' => 'POL'),
        620 => array('name' => 'Portugal','numeric-codes' => 620,'alpha-2-codes' => 'PT','alpha-3-codes' => 'PRT'),
        630 => array('name' => 'Puerto Rico','numeric-codes' => 630,'alpha-2-codes' => 'PR','alpha-3-codes' => 'PRI'),
        634 => array('name' => 'Qatar','numeric-codes' => 634,'alpha-2-codes' => 'QA','alpha-3-codes' => 'QAT'),
        638 => array('name' => 'Réunion','numeric-codes' => 638,'alpha-2-codes' => 'RE','alpha-3-codes' => 'REU'),
        642 => array('name' => 'Romania','numeric-codes' => 642,'alpha-2-codes' => 'RO','alpha-3-codes' => 'ROU'),
        643 => array('name' => 'Russian Federation','numeric-codes' => 643,'alpha-2-codes' => 'RU','alpha-3-codes' => 'RUS'),
        646 => array('name' => 'Rwanda','numeric-codes' => 646,'alpha-2-codes' => 'RW','alpha-3-codes' => 'RWA'),
        652 => array('name' => 'Saint Barthélemy','numeric-codes' => 652,'alpha-2-codes' => 'BL','alpha-3-codes' => 'BLM'),
        654 => array('name' => 'Saint Helena, Ascension and Tristan da Cunha','numeric-codes' => 654,'alpha-2-codes' => 'SH','alpha-3-codes' => 'SHN'),
        659 => array('name' => 'Saint Kitts and Nevis','numeric-codes' => 659,'alpha-2-codes' => 'KN','alpha-3-codes' => 'KNA'),
        662 => array('name' => 'Saint Lucia','numeric-codes' => 662,'alpha-2-codes' => 'LC','alpha-3-codes' => 'LCA'),
        663 => array('name' => 'Saint Martin (French part)','numeric-codes' => 663,'alpha-2-codes' => 'MF','alpha-3-codes' => 'MAF'),
        666 => array('name' => 'Saint Pierre and Miquelon','numeric-codes' => 666,'alpha-2-codes' => 'PM','alpha-3-codes' => 'SPM'),
        670 => array('name' => 'Saint Vincent and the Grenadines','numeric-codes' => 670,'alpha-2-codes' => 'VC','alpha-3-codes' => 'VCT'),
        882 => array('name' => 'Samoa','numeric-codes' => 882,'alpha-2-codes' => 'WS','alpha-3-codes' => 'WSM'),
        674 => array('name' => 'San Marino','numeric-codes' => 674,'alpha-2-codes' => 'SM','alpha-3-codes' => 'SMR'),
        678 => array('name' => 'Sao Tome and Principe','numeric-codes' => 678,'alpha-2-codes' => 'ST','alpha-3-codes' => 'STP'),
        682 => array('name' => 'Saudi Arabia','numeric-codes' => 682,'alpha-2-codes' => 'SA','alpha-3-codes' => 'SAU'),
        686 => array('name' => 'Senegal','numeric-codes' => 686,'alpha-2-codes' => 'SN','alpha-3-codes' => 'SEN'),
        688 => array('name' => 'Serbia','numeric-codes' => 688,'alpha-2-codes' => 'RS','alpha-3-codes' => 'SRB'),
        690 => array('name' => 'Seychelles','numeric-codes' => 690,'alpha-2-codes' => 'SC','alpha-3-codes' => 'SYC'),
        694 => array('name' => 'Sierra Leone','numeric-codes' => 694,'alpha-2-codes' => 'SL','alpha-3-codes' => 'SLE'),
        702 => array('name' => 'Singapore','numeric-codes' => 702,'alpha-2-codes' => 'SG','alpha-3-codes' => 'SGP'),
        534 => array('name' => 'Sint Maarten (Dutch part)','numeric-codes' => 534,'alpha-2-codes' => 'SX','alpha-3-codes' => 'SXM'),
        703 => array('name' => 'Slovakia','numeric-codes' => 703,'alpha-2-codes' => 'SK','alpha-3-codes' => 'SVK'),
        705 => array('name' => 'Slovenia','numeric-codes' => 705,'alpha-2-codes' => 'SI','alpha-3-codes' => 'SVN'),
        90 => array('name' => 'Solomon Islands','numeric-codes' => 90,'alpha-2-codes' => 'SB','alpha-3-codes' => 'SLB'),
        706 => array('name' => 'Somalia','numeric-codes' => 706,'alpha-2-codes' => 'SO','alpha-3-codes' => 'SOM'),
        710 => array('name' => 'South Africa','numeric-codes' => 710,'alpha-2-codes' => 'ZA','alpha-3-codes' => 'ZAF'),
        239 => array('name' => 'South Georgia and the South Sandwich Islands','numeric-codes' => 239,'alpha-2-codes' => 'GS','alpha-3-codes' => 'SGS'),
        728 => array('name' => 'South Sudan','numeric-codes' => 728,'alpha-2-codes' => 'SS','alpha-3-codes' => 'SSD'),
        724 => array('name' => 'Spain','numeric-codes' => 724,'alpha-2-codes' => 'ES','alpha-3-codes' => 'ESP'),
        144 => array('name' => 'Sri Lanka','numeric-codes' => 144,'alpha-2-codes' => 'LK','alpha-3-codes' => 'LKA'),
        729 => array('name' => 'Sudan','numeric-codes' => 729,'alpha-2-codes' => 'SD','alpha-3-codes' => 'SDN'),
        740 => array('name' => 'Suriname','numeric-codes' => 740,'alpha-2-codes' => 'SR','alpha-3-codes' => 'SUR'),
        744 => array('name' => 'Svalbard and Jan Mayen','numeric-codes' => 744,'alpha-2-codes' => 'SJ','alpha-3-codes' => 'SJM'),
        748 => array('name' => 'Swaziland','numeric-codes' => 748,'alpha-2-codes' => 'SZ','alpha-3-codes' => 'SWZ'),
        752 => array('name' => 'Sweden','numeric-codes' => 752,'alpha-2-codes' => 'SE','alpha-3-codes' => 'SWE'),
        756 => array('name' => 'Switzerland','numeric-codes' => 756,'alpha-2-codes' => 'CH','alpha-3-codes' => 'CHE'),
        760 => array('name' => 'Syrian Arab Republic','numeric-codes' => 760,'alpha-2-codes' => 'SY','alpha-3-codes' => 'SYR'),
        158 => array('name' => 'Taiwan, Province of China','numeric-codes' => 158,'alpha-2-codes' => 'TW','alpha-3-codes' => 'TWN'),
        762 => array('name' => 'Tajikistan','numeric-codes' => 762,'alpha-2-codes' => 'TJ','alpha-3-codes' => 'TJK'),
        834 => array('name' => 'Tanzania, United Republic of','numeric-codes' => 834,'alpha-2-codes' => 'TZ','alpha-3-codes' => 'TZA'),
        764 => array('name' => 'Thailand','numeric-codes' => 764,'alpha-2-codes' => 'TH','alpha-3-codes' => 'THA'),
        626 => array('name' => 'Timor-Leste','numeric-codes' => 626,'alpha-2-codes' => 'TL','alpha-3-codes' => 'TLS'),
        768 => array('name' => 'Togo','numeric-codes' => 768,'alpha-2-codes' => 'TG','alpha-3-codes' => 'TGO'),
        772 => array('name' => 'Tokelau','numeric-codes' => 772,'alpha-2-codes' => 'TK','alpha-3-codes' => 'TKL'),
        776 => array('name' => 'Tonga','numeric-codes' => 776,'alpha-2-codes' => 'TO','alpha-3-codes' => 'TON'),
        780 => array('name' => 'Trinidad and Tobago','numeric-codes' => 780,'alpha-2-codes' => 'TT','alpha-3-codes' => 'TTO'),
        788 => array('name' => 'Tunisia','numeric-codes' => 788,'alpha-2-codes' => 'TN','alpha-3-codes' => 'TUN'),
        792 => array('name' => 'Turkey','numeric-codes' => 792,'alpha-2-codes' => 'TR','alpha-3-codes' => 'TUR'),
        795 => array('name' => 'Turkmenistan','numeric-codes' => 795,'alpha-2-codes' => 'TM','alpha-3-codes' => 'TKM'),
        796 => array('name' => 'Turks and Caicos Islands','numeric-codes' => 796,'alpha-2-codes' => 'TC','alpha-3-codes' => 'TCA'),
        798 => array('name' => 'Tuvalu','numeric-codes' => 798,'alpha-2-codes' => 'TV','alpha-3-codes' => 'TUV'),
        800 => array('name' => 'Uganda','numeric-codes' => 800,'alpha-2-codes' => 'UG','alpha-3-codes' => 'UGA'),
        804 => array('name' => 'Ukraine','numeric-codes' => 804,'alpha-2-codes' => 'UA','alpha-3-codes' => 'UKR'),
        784 => array('name' => 'United Arab Emirates','numeric-codes' => 784,'alpha-2-codes' => 'AE','alpha-3-codes' => 'ARE'),
        826 => array('name' => 'United Kingdom','numeric-codes' => 826,'alpha-2-codes' => 'GB','alpha-3-codes' => 'GBR'),
        840 => array('name' => 'United States','numeric-codes' => 840,'alpha-2-codes' => 'US','alpha-3-codes' => 'USA'),
        581 => array('name' => 'United States Minor Outlying Islands','numeric-codes' => 581,'alpha-2-codes' => 'UM','alpha-3-codes' => 'UMI'),
        858 => array('name' => 'Uruguay','numeric-codes' => 858,'alpha-2-codes' => 'UY','alpha-3-codes' => 'URY'),
        860 => array('name' => 'Uzbekistan','numeric-codes' => 860,'alpha-2-codes' => 'UZ','alpha-3-codes' => 'UZB'),
        548 => array('name' => 'Vanuatu','numeric-codes' => 548,'alpha-2-codes' => 'VU','alpha-3-codes' => 'VUT'),
        862 => array('name' => 'Venezuela, Bolivarian Republic of','numeric-codes' => 862,'alpha-2-codes' => 'VE','alpha-3-codes' => 'VEN'),
        704 => array('name' => 'Viet Nam','numeric-codes' => 704,'alpha-2-codes' => 'VN','alpha-3-codes' => 'VNM'),
        92 => array('name' => 'Virgin Islands, British','numeric-codes' => 92,'alpha-2-codes' => 'VG','alpha-3-codes' => 'VGB'),
        850 => array('name' => 'Virgin Islands, U.S.','numeric-codes' => 850,'alpha-2-codes' => 'VI','alpha-3-codes' => 'VIR'),
        876 => array('name' => 'Wallis and Futuna','numeric-codes' => 876,'alpha-2-codes' => 'WF','alpha-3-codes' => 'WLF'),
        732 => array('name' => 'Western Sahara','numeric-codes' => 732,'alpha-2-codes' => 'EH','alpha-3-codes' => 'ESH'),
        887 => array('name' => 'Yemen','numeric-codes' => 887,'alpha-2-codes' => 'YE','alpha-3-codes' => 'YEM'),
        894 => array('name' => 'Zambia','numeric-codes' => 894,'alpha-2-codes' => 'ZM','alpha-3-codes' => 'ZMB'),
        716 => array('name' => 'Zimbabwe','numeric-codes' => 716,'alpha-2-codes' => 'ZW','alpha-3-codes' => 'ZWE')
    );

    /**
     * @param $num
     *
     * @return mixed
     */
    public function numericToAlpha2Code($num)
    {
        if (array_key_exists($num, $this->data))
        {
            return $this->data[$num]['alpha-2-codes'];
        }

        return false;
    }

    /**
     * @param $num
     *
     * @return mixed
     */
    public function numericToName($num)
    {
        if (array_key_exists($num, $this->data))
        {
            return $this->data[$num]['name'];
        }

        return false;
    }

    /**
     *
     * @return array
     */
    public function getData()
    {
        return $this->data;
    }
}
